# Minmal playbook to enable SELinux, set it to enfocing mode, and using the targeted policy set
# based on /usr/share/doc/rhel-system-roles/selinux/example-selinux-playbook.yml

- name: Enforce the targeted policy
  hosts: localhost
  vars:
    selinux_policy: targeted
    selinux_state: enforcing

  tasks:
    - name: Configure SELinux
      block:
        - name: Include selinux role
          include_role:
            name: rhel-system-roles.selinux
      rescue:
        # Fail if failed for a different reason than selinux_reboot_required.
        - name: Handle errors
          fail:
            msg: "role failed"
          when: not selinux_reboot_required

        - name: Restart managed host
          reboot:

        - name: Wait for managed host to come back
          wait_for_connection:
            delay: 10
            timeout: 300

        - name: Reapply the role
          include_role:
            name: rhel-system-roles.selinux

